[[main]]
  identifier = "10things"
  name = "10 Things"
  url = "10things"
  weight = 40 

#[[main]]
#  identifier = "resources"
#  name = "Resources"
#  url = "resources"
#  weight = 30
#
#[[main]]
#  identifier = "updates"
#  name = "Updates"
#  url = "updates"
#  weight = 10
#
[[main]]
 identifier = "about"
 name = "About"
 url = "about"
 weight= 10

[[main]]
 identifier = "approach"
 name = "The Cure Approach"
 url = "about/approach"
 parent = "about"
 weight = 10

[[main]]
 identifier = "news"
 name = "News"
 url = "news"
 weight = 20

#[[main]]
#  identifier = "membership"
#  name = "Membership"
#  url = "membership"
#  weight = 40
#
#[[main]]
#  identifier = "people"
#  name = "People"
#  url = "people"
#  weight = 50
