[[main]]
  identifier = "resources"
  name = "Resources"
  url = "resources"
  weight = 30

[[main]]
  identifier = "updates"
  name = "Updates"
  url = "updates"
  weight = 10

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 20

[[main]]
  identifier = "membership"
  name = "Membership"
  url = "membership"
  weight = 40

[[main]]
  identifier = "people"
  name = "People"
  url = "people"
  weight = 50
